services:
  cloud-server:
    image: ${IMAGE:-ghcr.io/javidahmed64592/cloud-server:latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloud-server
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
      - NGINX_PROXY_URL=${NGINX_PROXY_URL:-}
    volumes:
      - ./.env:/app/.env
      - ./logs:/app/logs
      - ./data:/app/data
      - ${SERVER_DIRECTORY:-./server}:/app/server
    restart: unless-stopped
